# This workflow will build and test the /test/ project with twcli, inflator, and goboscript.
# This runs on pull request or on any push to the repository
# based on https://www.youtube.com/watch?v=uFcXrWT4f80
name: Run tests

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
  release:
    types: [prereleased, published]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
          
      - name: Set up rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set up goboscript
        run: |
          export PATH="$PATH:~/.local/bin"
          export PATH="$PATH:~/.cargo/bin"
          if ! command -v cargo >/dev/null 2>&1; then
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          fi
          cargo install --git https://github.com/aspizu/goboscript
        # above code is from:
        # run: curl -fsSL https://raw.githubusercontent.com/aspizu/goboscript/refs/heads/main/install.sh | sh 
        # but backpack and sb2gs have been removed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U turbowarp-cli
          pip install -U inflator
          playwright install --with-deps
      
      - name: Build package
        run: |
          ls -l
          inflate install .
          cd test
          inflate install -r inflator.toml
          inflate
          goboscript build

      - name: debug twcli assets
        run: |
          cd /opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/site-packages/twcli/
          ls -l
          twcli -h
      
      - name: Test with tw-cli
        run: |
          cd test
          ls -l
          twcli run ./test.sb3 -R
