# This workflow will run pytest in the repository directory
# This runs on pull request or on any push to the repository
# based on https://www.youtube.com/watch?v=uFcXrWT4f80
name: Run tests

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
  release:
    types: [prereleased, published]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
          
      - name: Set up rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set up goboscript
        run: curl -fsSL https://raw.githubusercontent.com/aspizu/goboscript/refs/heads/main/install.sh | sh

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install turbowarp-cli
          pip install inflator
      
      - name: Build package
        run: |
          ls -l
          inflate install .
          cd test
          inflate
          goboscript build
          
      - name: Test with tw-cli
        run: |
          twcli run test.sb3 -R
